### ISSUE TITLE
Python example type error (pyshader).

### ISSUE THREAD

**Issue by CaiusTSM** [EthicalML/vulkan-kompute#111] opened 2021-01-12 20:28 UTC
The first python example on https://kompute.cc/overview/python-package.html causes the following type error:
```
    mgr.eval_algo_data_def([tensor_in_a, tensor_in_b, tensor_out], compute_shader_multiply.to_spirv())
TypeError: eval_algo_data_def(): incompatible function arguments. The following argument types are supported:
    1. (self: kp.Manager, arg0: List[kp.Tensor], arg1: List[str]) -> None

Invoked with: <kp.Manager object at 0x7f5a042067f0>, [<kp.Tensor object at 0x7f5a0420e5f0>, <kp.Tensor object at 0x7f5a0420e5b0>, <kp.Tensor object at 0x7f5a03cb0d70>], b'\x03\x02#\x07\x00\x03\x01\x00\x00\x00\x00\x00&\x00\x00\x00\x00\x00\x00\x00\x11\x00\x02\x00\x01\x00\x00\x00\x0e\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0f\x00\x06\x00\x05\x00\x00\x00\x01\x00\x00\x00main\x00\x00\x00\x00\x08\x00\x00\x00\x10\x00\x06\x00\x01\x00\x00\x00\x11\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x05\x00\x04\x00\x01\x00\x00\x00main\x00\x00\x00\x00\x05\x00\x04\x00\x08\x00\x00\x00index\x00\x00\x00\x05\x00\x04\x00\r\x00\x00\x00data1\x00\x00\x00\x05\x00\x03\x00\x0e\x00\x00\x000\x00\x00\x00\x05\x00\x04\x00\x11\x00\x00\x00data2\x00\x00\x00\x05\x00\x04\x00\x14\x00\x00\x00data3\x00\x00\x00\x05\x00\x03\x00\x16\x00\x00\x00i\x00\x00\x00G\x00\x04\x00\x08\x00\x00\x00\x0b\x00\x00\x00\x1c\x00\x00\x00G\x00\x04\x00\n\x00\x00\x00\x06\x00\x00\x00\x04\x00\x00\x00H\x00\x05\x00\x0b\x00\x00\x00\x00\x00\x00\x00#\x00\x00\x00\x00\x00\x00\x00G\x00\x03\x00\x0b\x00\x00\x00\x03\x00\x00\x00G\x00\x04\x00\r\x00\x00\x00"\x00\x00\x00\x00\x00\x00\x00G\x00\x04\x00\r\x00\x00\x00!\x00\x00\x00\x00\x00\x00\x00H\x00\x05\x00\x0f\x00\x00\x00\x00\x00\x00\x00#\x00\x00\x00\x00\x00\x00\x00G\x00\x03\x00\x0f\x00\x00\x00\x03\x00\x00\x00G\x00\x04\x00\x11\x00\x00\x00"\x00\x00\x00\x00\x00\x00\x00G\x00\x04\x00\x11\x00\x00\x00!\x00\x00\x00\x01\x00\x00\x00H\x00\x05\x00\x12\x00\x00\x00\x00\x00\x00\x00#\x00\x00\x00\x00\x00\x00\x00G\x00\x03\x00\x12\x00\x00\x00\x03\x00\x00\x00G\x00\x04\x00\x14\x00\x00\x00"\x00\x00\x00\x00\x00\x00\x00G\x00\x04\x00\x14\x00\x00\x00!\x00\x00\x00\x02\x00\x00\x00\x13\x00\x02\x00\x02\x00\x00\x00!\x00\x03\x00\x03\x00\x00\x00\x02\x00\x00\x00\x15\x00\x04\x00\x05\x00\x00\x00 \x00\x00\x00\x01\x00\x00\x00\x17\x00\x04\x00\x06\x00\x00\x00\x05\x00\x00\x00\x03\x00\x00\x00 \x00\x04\x00\x07\x00\x00\x00\x01\x00\x00\x00\x06\x00\x00\x00;\x00\x04\x00\x07\x00\x00\x00\x08\x00\x00\x00\x01\x00\x00\x00\x16\x00\x03\x00\t\x00\x00\x00 \x00\x00\x00\x1d\x00\x03\x00\n\x00\x00\x00\t\x00\x00\x00\x1e\x00\x03\x00\x0b\x00\x00\x00\n\x00\x00\x00 \x00\x04\x00\x0c\x00\x00\x00\x02\x00\x00\x00\x0b\x00\x00\x00;\x00\x04\x00\x0c\x00\x00\x00\r\x00\x00\x00\x02\x00\x00\x00+\x00\x04\x00\x05\x00\x00\x00\x0e\x00\x00\x00\x00\x00\x00\x00\x1e\x00\x03\x00\x0f\x00\x00\x00\n\x00\x00\x00 \x00\x04\x00\x10\x00\x00\x00\x02\x00\x00\x00\x0f\x00\x00\x00;\x00\x04\x00\x10\x00\x00\x00\x11\x00\x00\x00\x02\x00\x00\x00\x1e\x00\x03\x00\x12\x00\x00\x00\n\x00\x00\x00 \x00\x04\x00\x13\x00\x00\x00\x02\x00\x00\x00\x12\x00\x00\x00;\x00\x04\x00\x13\x00\x00\x00\x14\x00\x00\x00\x02\x00\x00\x00 \x00\x04\x00\x15\x00\x00\x00\x07\x00\x00\x00\x05\x00\x00\x00 \x00\x04\x00\x17\x00\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00 \x00\x04\x00\x1d\x00\x00\x00\x02\x00\x00\x00\t\x00\x00\x00 \x00\x04\x00 \x00\x00\x00\x02\x00\x00\x00\t\x00\x00\x00 \x00\x04\x00$\x00\x00\x00\x02\x00\x00\x00\t\x00\x00\x006\x00\x05\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\xf8\x00\x02\x00\x04\x00\x00\x00;\x00\x04\x00\x15\x00\x00\x00\x16\x00\x00\x00\x07\x00\x00\x00A\x00\x05\x00\x17\x00\x00\x00\x18\x00\x00\x00\x08\x00\x00\x00\x0e\x00\x00\x00=\x00\x04\x00\x05\x00\x00\x00\x19\x00\x00\x00\x18\x00\x00\x00>\x00\x03\x00\x16\x00\x00\x00\x19\x00\x00\x00=\x00\x04\x00\x05\x00\x00\x00\x1a\x00\x00\x00\x16\x00\x00\x00=\x00\x04\x00\x05\x00\x00\x00\x1b\x00\x00\x00\x16\x00\x00\x00A\x00\x06\x00\x1d\x00\x00\x00\x1e\x00\x00\x00\r\x00\x00\x00\x0e\x00\x00\x00\x1a\x00\x00\x00=\x00\x04\x00\t\x00\x00\x00\x1f\x00\x00\x00\x1e\x00\x00\x00A\x00\x06\x00 \x00\x00\x00!\x00\x00\x00\x11\x00\x00\x00\x0e\x00\x00\x00\x1b\x00\x00\x00=\x00\x04\x00\t\x00\x00\x00"\x00\x00\x00!\x00\x00\x00\x85\x00\x05\x00\t\x00\x00\x00\x1c\x00\x00\x00\x1f\x00\x00\x00"\x00\x00\x00=\x00\x04\x00\x05\x00\x00\x00#\x00\x00\x00\x16\x00\x00\x00A\x00\x06\x00$\x00\x00\x00%\x00\x00\x00\x14\x00\x00\x00\x0e\x00\x00\x00#\x00\x00\x00>\x00\x03\x00%\x00\x00\x00\x1c\x00\x00\x00\xfd\x00\x01\x008\x00\x01\x00'
```
It wants a `List[str]`, but is given bytes from the `to_spriv` function. I tried casting with `list(str(compute_shader_multiply.to_spirv()))`, but that results in a segfault.

**Comment by aliPMPAINT** [comment] 2021-01-12 21:03
Afaik, `compute_shader_multiply.to_spirv()` only works with Nvidia GPUs(#107), in a nutshell using raw shaders code won't work with other GPUs. Just remove `, compute_shader_multiply.to_spirv()` from `mgr.eval_algo_data_def([tensor_in_a, tensor_in_b, tensor_out], compute_shader_multiply.to_spirv())`.

**Comment by aliPMPAINT** [comment] 2021-01-12 21:35
Have you installed Vulkan SDK?

**Comment by CaiusTSM** [comment] 2021-01-12 22:10
Yes, I have the Vulkan SDK installed. I have an AMD GPU, does pyshader only work with Nvidia GPUs?

**Comment by aliPMPAINT** [comment] 2021-01-13 05:32
No, mine is also AMD(Radeon HD 7770) but the code works fine. It appears that the issue is with (pyshader)[https://github.com/pygfx/pyshader], it didn't convert glsl to spirv ; with `list(str(compute_shader_multiply.to_spirv()))` I don't get a segfault. I suggest that you open an issue there.

**Comment by aliPMPAINT** [comment] 2021-01-13 06:00
What version are you using? Mine is `1. (self: kp.Manager, arg0: List[kp.Tensor], arg1: bytes) -> None` not `1. (self: kp.Manager, arg0: List[kp.Tensor], arg1: List[str]) -> None`

**Comment by aliPMPAINT** [comment] 2021-01-13 06:12
I've downgraded to version 0.4.1 and got the same error, I think it's a change due to [this commit](https://github.com/EthicalML/vulkan-kompute/commit/6c6132942247bcc7a04144b9f29e12eacc58b74e), I suggest you update kp to the latest version (0.5.1).

**Comment by axsaucedo** [comment] 2021-01-13 09:13
Good shout @aliPMPAINT, yes it does seem like it most probably is due to that change, @CaiusTSM can you confirm which version of the python are you using? Can you try it with the latest 0.5.1?

**Comment by CaiusTSM** [comment] 2021-01-13 17:14
Yes, I am using version 0.4.1. I have built and installed from source (via `pip install .`) and the example works now (version 0.5.2). The pypi kompute package (https://pypi.org/project/kompute/#files) does not seem to be kept up to date. Could you update it (unless this is not an official pypi package, not sure)? This seems like a very important version update. Prebuilt binaries would also be appreciated as on small ARM systems build times are very long. Maybe open a separate issue for this?

**Comment by axsaucedo** [comment] 2021-01-13 17:19
Oh I see, good shout @CaiusTSM - initially I created the `kompute` package, but then decided to release to `kp` instead. I will have a look at either keeping both of them updated, or closing the `kompute` package.

**Closed** 2021-01-16 14:49 UTC
