### ISSUE TITLE
Add support for push constants

### ISSUE THREAD

**Issue by alexander-g** [EthicalML/vulkan-kompute#106] opened 2021-01-02 18:39 UTC
Currently only tensors are implemented which are based on buffers. They can be used for large amounts of data but are inefficient for small frequently changing values, e.g. when chaining the same shader. This is what push constants are for.
I could try to contribute, might need some input how the API should look like.

**Comment by axsaucedo** [comment] 2021-01-04 19:11
I completely agree @alexander-g, this is already covered in https://github.com/EthicalML/vulkan-kompute/issues/54 and is scheduled for 0.7.0 and more specifically https://github.com/EthicalML/vulkan-kompute/issues/12 which is scheduled for 0.5.2. Currerntly it's not clear what is the best way to expose these, as currently there is no standard way to "modify" data through the Sequence / Manager interface. I would be open to suggestions on what the API for this coudl look like, as it's currently not set in stone.

**Comment by axsaucedo** [comment] 2021-02-21 13:17
Duplicate of #54

**Closed by axsaucedo** 2021-02-21 13:17 UTC
